# Generated by Django 3.1.7 on 2021-02-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.CharField(max_length=50)),
                ('amazon_email', models.EmailField(max_length=254)),
                ('amazon_password', models.CharField(help_text='Password, up to 40 characters', max_length=40)),
                ('zipcode', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=30)),
            ],
        ),
    ]
