# Generated by Django 3.1.7 on 2021-03-04 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retaildata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retaileraccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='retaileraccount',
            name='amazon_email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='retaileraccount',
            name='amazon_password',
            field=models.CharField(help_text='Password, up to 40 characters', max_length=100),
        ),
        migrations.CreateModel(
            name='CodeRedemption',
            fields=[
                ('gift_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('redemption_date', models.DateTimeField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('account_where_to_redeem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='retaildata.retaileraccount')),
            ],
        ),
    ]
