# Generated by Django 3.1.7 on 2021-03-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retaildata', '0002_auto_20210304_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retaileraccount',
            old_name='zipcode',
            new_name='zip_code',
        ),
    ]
